### PR TITLE
Add the I2C driver for BMP180

### PR DESCRIPTION
**Pull request by elopio**

### CODE REVIEW

**Comment by elopio** [comment]
This is my first attempt at playing with i2c, so any feedback will be appreciated.

**Comment by deadprogram** [comment]
Hi, @elopio this is great, thank you. I have a couple of comments/requests.

- Can you please resubmit against the `dev` branch instead of `master`. This allows us to have a proper release of new features. due to how golang fetches packages.
- For i2c drivers, instead of a goroutine to update the data, the typical pattern has been to let the user call at whatever periodicity they wish. The HMC6352 is a good example of this. The `Start()` method just initializes the i2c commication and does whatever configuration is needed. In your case, that would mean removing lines 113-127 of bmp180_driver.go

Thanks again for working on this!

**Comment by elopio** [comment]
on it.

**Comment by elopio** [comment]
@deadprogram thanks for the review. Please check it again.
I moved the mode as an argument to the Pressure method. I'm not sure if I should have left it as an attribute of the driver.

**Comment by deadprogram** [comment]
Thank you very much for this, @elopio now merging.

**Comment by elopio** [comment]
\o/ thank you!

**Pull request merged**
