### PR TITLE
bugfix for digispark i2c readwritebyte

### LINKED ISSUE #787: digispark i2c bug in ReadByte() & WriteByte()
ReadByte()/WriteByte() don't rely on Read(buf)/Write(buf) but call the "littlewire.i2cRead(b, 1, 1)"/"littleWire.i2cWrite(b, 1, 1)" directly. This results in missing START-condition, which is normally done with littleWire.i2cStart(c.address, 1), refer to Read(buf)/Write(buf)-function. Therefore all functions based on ReadByte()/WriteByte will not working like expected, which is currently only ReadByteData(). For working example, see firmata_i2c.go

I will provide a bugfix asap, this could be a workaround:
func (c *digisparkI2cConnection) ReadByte() (val byte, err error) {
	buf := []byte{0}
	if _, err = c.Read(buf);	err != nil {
		return
	}
	val = buf[0]
	return
}

### PR DESCRIPTION
**Pull request by gen2thomas**
will fix #787
additionally:
* split unit tests for i2c
* add unit tests for nearly all functions (e.g. no test for WriteBlockData yet)

### CODE REVIEW

**Comment by deadprogram** [comment]
Thank you @gen2thomas for your contribution. I will test this PR in the next few days.

**Comment by gen2thomas** [comment]
@deadprogram sounds good. Will support to make progress.

**Comment by gen2thomas** [comment]
Hello @deadprogram, how can I help you to speed up completion of this PR (and maybe others)?

**Comment by gen2thomas** [comment]
@deadprogram do you have remarks after your test?

**Comment by deadprogram** [comment]
Overdue to merge this. Thanks again for working on it @gen2thomas

**Pull request merged**
