### PR TITLE
fixed undefined method errors

### PR DESCRIPTION
**Pull request by radovskyb**
Replaced `gobot` references that were returning undefined method errors with the correct `driver` references.

### CODE REVIEW

**Comment by deadprogram** [comment]
Hi @radovskyb thanks for the corrections, but could you please resubmit this PR against the `dev` branch? Thank you!

**Comment by radovskyb** [comment]
Haha sorry whoops! Done!

**Comment by deadprogram** [comment]
And of course now "This branch has conflicts that must be resolved" :)

**Comment by radovskyb** [comment]
I'll close the request and re-submit without the pebble/doc.go file?

**Comment by deadprogram** [comment]
That would probably work. I suggest making sure to always start edits from a new feature branch off of the `dev` branch, since that is where all the action is right now.

**Pull request closed without merging**
