### PR TITLE
Adding stepper motor module

### PR DESCRIPTION
**Pull request by coding-yogi**
This module will allow an user to control a 4-wired stepper motor with a Single, Dual and Half stepping modes

### CODE REVIEW

**Comment by deadprogram** [comment]
This is great @coding-yogi thank you.

Any chance you could also add a very basic example of it in use to `examples`? This also helps when we're preparing the docs.

Thanks!

**Comment by coding-yogi** [comment]
Sure, let me add one

**Comment by coding-yogi** [comment]
I am able to drive motor with raspi adaptor but not with gpg3, any pointers?
I see this error : **open /dev/spidev0.1: no such file or directory**.
 Here is my [code](https://gist.github.com/coding-yogi/41988b6928c5a32ac66a5c50af7d1035)

**Comment by deadprogram** [comment]
The pin mapping/naming on the GoPiGo can be found here:

https://github.com/hybridgroup/gobot/blob/master/platforms/dexter/gopigo3/driver.go#L619

Seems like you would be better off with just a pure Raspi example. Even when using with the GoPiGo3, if you connected the pins to the stepper controller, you would just connect the Raspi pins, and use the GoPiGo3 grove ports for other devices.

**Comment by deadprogram** [comment]
Thanks again for contributing @coding-yogi now merging.

**Pull request merged**
