### PR TITLE
Update ble 0.10

### PR DESCRIPTION
**Pull request by deadprogram**
## Solved issues and/or description of the change

Changes needed for compatibility with the new version of the `bluetooth` package.

## Manual test

- OS and Version (Win/Mac/Linux): Linux
- Adaptor(s) and/or driver(s): Ran `examples/ble_minidrone.go` successfully.

## Checklist

- [X] The PR's target branch is 'hybridgroup:dev'
- [X] New and existing unit tests pass locally with my changes (e.g. by run `make test_race`)
- [X] No linter errors exist locally (e.g. by run `make fmt_check`)
- [X] I have performed a self-review of my own code

### CODE REVIEW

**Comment by deadprogram** [comment]
@gen2thomas I will update this PR shortly once the new release of the TinyGo `bluetooth` package is completed, and then it should be good for merge.

**Comment by gen2thomas** [comment]
Hi @deadprogram , thanks for your work. Just give me a hint, when the PR is ready to review.

**Comment by gen2thomas** [comment]
Hi @deadprogram , please can you rebase and finally switch to 0.10.

Thanks, Thomas

**Comment by deadprogram** [comment]
Done.

**Pull request merged**
