### PR TITLE
basic mpr121 driver

### PR DESCRIPTION
**Pull request by mattetti**
from what I saw you need to write the interrupt to a pin to get a notification that the reading has changed

### CODE REVIEW

**Comment by deadprogram** [comment]
Hi @mattetti is this ready for merge?

**Comment by mattetti** [comment]
Not really... There is something wrong, we aren't getting the data, I'll need someone help to get it to work.

**Comment by deadprogram** [comment]
Hi, @mattetti anything I can assist with on this?

**Comment by mattetti** [comment]
you can try to make it work or reject the PR. I don't think gobot supports interrupts and that seems to be the main issue here.

**Comment by deadprogram** [comment]
You mean interrupts on a connected microcontroller? Please elaborate a bit, if you will.

**Comment by deadprogram** [comment]
Closing this, will revisit in Gobot 1.1

**Comment by steffenmllr** [comment]
Any chance to add support for the mpr121 in 1.8 ?

**Comment by mattetti** [comment]
@steffenmllr the reason I stopped is because gobot doesn't support interrupts, once that's being addressed, then I think it shouldn't be an issue to finish the driver.

**Pull request closed without merging**
