### PR TITLE
Fix incorrect change state

### PR DESCRIPTION
**Pull request by vlastv**

### CODE REVIEW

**Comment by deadprogram** [comment]
Hi @vlastv thank for for noticing this issue.

Could you please resubmit this PR against the `dev` branch? Thank you very much!

**Comment by vlastv** [comment]
I fix test, but driver incorrect use currentMode.
If use speedPin and forwardPin, after call On() currentMode changed to `analog`.

I will refactoring motor driver for fix it.

**Comment by vlastv** [comment]
@deadprogram you can restart job https://travis-ci.org/hybridgroup/gobot/jobs/221384585 ?

**Comment by deadprogram** [comment]
Just did it, @vlastv

**Comment by vlastv** [comment]
@deadprogram, thx. Test passed:)

**Comment by deadprogram** [comment]
Thank you very much @vlastv now merging.

**Pull request merged**
