### PR TITLE
Fix brightness apa102

### PR DESCRIPTION
**Pull request by air1bzz**
#664

### CODE REVIEW

**Comment by deadprogram** [comment]
Hi @air1bzz thank you very much for the PR.

I think that it would probably be better to use the Alpha channel as the brightness, instead of having the additional wrapper class for `Color`. That seems to fit the spirit of the API.

What do you think?

**Comment by air1bzz** [comment]
Yes, you're right, I initially wanted to use `Color` in a constructor to avoid brigthness overbounds (0-31). But I found it quite verbose and @MikeZange's proposal in #667 is definitely what we need.

I would like to keep the idea of setting a default brightness in driver's initialization:
if you want to control brightness only with Alpha from `color.RGBA` you can set driver's brightness to `0`.

**Comment by deadprogram** [comment]
Seems like a good idea.

**Comment by deadprogram** [comment]
Hi @air1bzz I merged this commit into `dev`  https://github.com/hybridgroup/gobot/commit/70fd202030bfa3fa0898c837bce460f9a702ecf5 so you should probably close this PR and open a new one with whatever other changes you propose.

Thank you!

**Comment by air1bzz** [comment]
Closing PR, new one updated at https://github.com/hybridgroup/gobot/pull/671

**Pull request closed without merging**
