### PR TITLE
Fixing travis

### PR DESCRIPTION
**Pull request by danacr**
Includes temporary fix for https://github.com/bugst/go-serial/issues/71

### CODE REVIEW

**Comment by danacr** [comment]
Used https://config.travis-ci.com/explore for reference

**Comment by deadprogram** [comment]
We really need this, thank you very much @danacr for these fixes.

Now merging.

**Comment by msclp** [comment]
still having certificate issue
```
package go.bug.st/serial.v1: unrecognized import path "go.bug.st/serial.v1" (https fetch: Get https://go.bug.st/serial.v1?go-get=1: x509: certificate has expired or is not yet valid)
```

**Comment by danacr** [comment]
@msclp could you be a bit more specific? A reference to a PR would be great

**Comment by msclp** [comment]
@danacr I'm running command `go get -d -u gobot.io/x/gobot/...` and receiving the message from above

**Comment by danacr** [comment]
@msclp the issue is unrelated to this pull request. Use the following command till https://github.com/bugst/go-serial/issues/71 gets fixed:

```
GIT_SSL_NO_VERIFY=1 go get -insecure -d -u gobot.io/x/gobot/...
```

**Comment by danacr** [comment]
The workaround should no longer be required since https://github.com/bugst/go-serial/issues/71 was closed

**Pull request merged**
