### PR TITLE
Added support for Dualsense joystick (PlayStation 5)

### PR DESCRIPTION
**Pull request by jig**
Added support for PlayStation 5 Dualsense joystick.

Code derived from Dualshock 4:
- buttons remapped to appropriate IDs
- L2 and R2 are now "axis" instead of "buttons"
- New "create" button (instead of "share" button)
- examples/joystick_ps5.go file as example code

### CODE REVIEW

**Comment by jig** [comment]
Example is being build. It has not to. Fixing it now.

**Comment by jig** [comment]
Example building is disabled now.

**Comment by gen2thomas** [comment]
@jig unfortunatelly I have no such platform and device to test the new driver, but from the code review perspective, it looks good to me. 

@deadprogram is there anything for you, what is against the merge?

**Comment by gen2thomas** [comment]
Hi @jig, please can you change the [target branch to dev](https://github.com/hybridgroup/gobot/blob/release/CONTRIBUTING.md#target-branch). Meanwhile I set it back to draft.

**Comment by jig** [comment]
Hmm, I think I messed the history of this PR @gen2thomas trying to get changes from dev.
I'll try to redo this from scratch and I'll try to create a brand new (and hopefully correct PR).

I will close this PR when I will complete the new one.

**Comment by jig** [comment]
This PR has been superseded by https://github.com/hybridgroup/gobot/pull/880.

**Pull request closed without merging**
