### PR TITLE
Add tflight hotas x controller

### PR DESCRIPTION
**Pull request by SMerrony**
Add the Thrustmaster T-Flight HOTAS X flight controller

(My first PR - hope I got things right...)

### CODE REVIEW

**Comment by deadprogram** [comment]
Hi @SMerrony thank you for this PR. 

The chance you made to `scanner.go` is incompatible with the latest SDL. This is the reason that the tests are failing on Travis. The reason they pass on AppVeyor (Windows) is that AppVeyor uses an SDL build.

I am going to make a change to exclude the scanner.go from the test run anyhow, since it is not intentional that it run as part of the tests.

Now merging, thanks again for the PR.

**Comment by jadr2ddude** [comment]
@deadprogram just for reference, what version of SDL are you using that does not pass? I had run the build with version 2.0.8 on my local machine.

**Comment by deadprogram** [comment]
We should probably install that version ourselves on Travis ala https://stackoverflow.com/questions/48733550/how-to-add-a-recent-version-of-libsdl2-to-my-travis-ci-build

**Comment by deadprogram** [comment]
Also, we need to update to https://github.com/veandco/go-sdl2/releases/tag/v0.3

**Pull request merged**
