### PR TITLE
Use go1.7.5 to build the snap

### PR DESCRIPTION
**Pull request by elopio**

### CODE REVIEW

**Comment by deadprogram** [comment]
Hi @elopio thanks for this update.

Merging...

**Comment by deadprogram** [comment]
On a related note, I've just created this page which needs some info filled in: https://gobot.io/documentation/guides/snapcraft/ 

The repo is here https://github.com/hybridgroup/gobot-site/blob/master/source/documentation/guides/snapcraft.html.haml

:)

**Comment by elopio** [comment]
oh, that's so nice :D
I'm on vacations next week, and I will use a few of those days to play with my hardware toys. I'll have some good info to fill there afterwards. And hopefully also the gort basics working.

@deadprogram now, why don't you push this gobot snap to the store? It would be really useful for us to get your feedback there. https://snapcraft.io/docs/build-snaps/publish

Anything that you hate, that you find wrong or that you would like to see improved, please let me know.

**Comment by deadprogram** [comment]
I thought I already had! I had done everything but the final release step. In any case:

```
$ snap info gobot
name:      gobot
summary:   "Gobot is a framework for robotics, physical computing, and IoT."
publisher: deadprogram
description: |
  Gobot is a framework using the Go programming language for robotics, physical
  computing, and the Internet of Things.
  It provides a simple, yet powerful way to create solutions that incorporate
  multiple, different hardware devices at the same time.
  
channels:         
  beta:   dev (2) 978kB -
  edge:   dev (2) 978kB -
```

**Pull request merged**
