### PR TITLE
add ultrasonic support for i2c driver

### PR DESCRIPTION
**Pull request by merlindorin**
Add new i2c feature for grovepi.

I use this code with the grove ultra sonic ranger : https://www.seeedstudio.com/Grove-Ultrasonic-Distance-Sensor.html

Mainly based on : https://github.com/DexterInd/GrovePi/blob/3b43647a4c87a892578a6818d8d55d16d932edba/Script/multi_grovepi_installer/grovepi3.py#L191

Feel free to comment, accept or refused it ^^

btw : nice project ;)

### CODE REVIEW

**Comment by deadprogram** [comment]
Hi @merlindorin thank you very much for this awesome contribution! Not sure why the build is failing but that appears to be unrelated to this PR. 

Any chance you might be able to also add a test to https://github.com/hybridgroup/gobot/blob/dev/drivers/i2c/grovepi_driver_test.go that covers this new function? :)

**Comment by merlindorin** [comment]
hi @deadprogram 
Ofc for adding test. I will do that this evening ;). I will also try to add some doc.

Btw, same feeling for travis... there is nothing in my pr that can break travis :/

**Comment by merlindorin** [comment]
@deadprogram sorry for being late. Just add a dumb test. 

We need a connection in initTestGrovePiDriver.

What do you think?

**Comment by merlindorin** [comment]
with updated tests ;)

**Comment by deadprogram** [comment]
Hi @merlindorin thanks for adding the tests.

We just merged a fix for the Travis build problem.

Could you please rebase your PR against the dev branch?

Thank you!

**Comment by merlindorin** [comment]
@deadprogram 6months later... back to fun.

I rebased my commit to dev last version ;).

(and sorry for the delay)

**Comment by deadprogram** [comment]
Thanks for the PR @merlindorin merging at long last!

**Pull request merged**
