### PR TITLE
Adds tests for grove drivers

### PR DESCRIPTION
**Pull request by wfernandes**
Signed-off-by: Warren Fernandes <warren.f.fernandes@gmail.com>

- Tried to write the tests without depending on un-exported properties like the `halt` channel.

### CODE REVIEW

**Comment by wfernandes** [comment]
Just noticed that the build failed because `t.Run()` is not available in go1.6 

If support for go1.6 is required I can update the tests to not use [Subtests feature of 1.7](https://blog.golang.org/subtests)

**Comment by deadprogram** [comment]
Hi @wfernandes thanks for working on this. Currently we're trying to always target the latest Golang release, as well as maintain backwards compatibility with the release immediately before the current one. Hence the dev build right now uses https://github.com/hybridgroup/gobot/blob/dev/.travis.yml#L6-L8

If you would not mind making the change your suggest for golang 1.6+ I think many users would appreciate it, as would I. Thank you!

**Comment by wfernandes** [comment]
@deadprogram Sure. Will make the changes.

**Comment by deadprogram** [comment]
Thanks, @wfernandes merging.

**Pull request merged**
