### PR TITLE
mavlink: add a Mavlink-over-UDP adaptor.

### PR DESCRIPTION
**Pull request by nzmichaelh**
Tested against the current version of mavproxy and QGroundControl, where mavproxy converts serial to UDP.

### CODE REVIEW

**Comment by deadprogram** [comment]
Hi @nzmichaelh this is really great, we really needed this capability. Thank you for working on it.

Could you please update the README with info on how to use the UDP adaptor, and also ideally add an example showing it in use?

Thanks again for your contributions!

**Comment by nzmichaelh** [comment]
Done.  PTAL.

**Comment by deadprogram** [comment]
Thank you, @nzmichaelh that will make it a lot easier for people to get started.

On related note: I was looking at https://github.com/liamstask/go-mavlink a while back, specifically for the purpose of parsing the various dialects of packets. Any thoughts on that?

In the meantime, I will merge this PR. Thanks again for working on it.

**Comment by deadprogram** [comment]
Hello again @nzmichaelh I was adding some test coverage to the UDPAdaptor, and I noticed that it seemed like this change is needed to be able to send messages: https://github.com/hybridgroup/gobot/commit/5817b7d8de7985c3d442f8d90a4950df38a2e83e

Perhaps your real-world code is listen only, or maybe I am missing something here. What do you think?

**Comment by deadprogram** [comment]
@nzmichaelh I've made a few changes in the branch https://github.com/hybridgroup/gobot/tree/feature/mavlink-tests perhaps you can test it with your hardware and make sure it still works as you expect. Also, my question about sending message still applies.

Thanks!

**Comment by deadprogram** [comment]
@nzmichaelh my updated code with tests and the change to `Write()` are now in the `dev` branch. Please verify that it still functions for you as you expect. Thanks again for working on this.

**Pull request merged**
