### PR TITLE
Dsockwell bme280 2017

### PR DESCRIPTION
**Pull request by dsockwell**
I transcribed the formulas for humidity calculation and also the correct derivation of the humidity calibration constants H4 and H5.

This needs to be tested with a working bme280, as I have discovered that mine is no longer fully functioning. I can try a spare soon.

It would be useful to record a known-good i2c dump from a working bme280 by running:
`i2cdump 1 0x76`
and recording the output. The test case can be written with hex values from the hex dump rather than values from the bmp180 datasheet which don't have humidity calibration or measurement values.

### CODE REVIEW

**Comment by deadprogram** [comment]
Hi @dsockwell so got confused about which sensor was which, with all the variations.

The BME280 is a BMP280 with the humidity sensor, NOT the same as the BMP180. Sorry about the mistake on my part.

In any case, I have now updated my https://github.com/hybridgroup/gobot/tree/feature/i2c/bme280 branch with your commits from this branch, plus a few others that I put in place.

Still need to implement a number the functions, all of which have been marked with "TODO" in the branch. 

I think only the BMP280 functions will need to be implemented, since the BME280 should be able to pick up the shared functionality.

If you are able to help further, it would be hugely appreciated. If not I will continue to work on it later this week. Thanks!

**Comment by dsockwell** [comment]
I have verified that the official drivers from Bosch perform the same temperature calculation on the BMP180 as on BMP280. 

https://github.com/BoschSensortec/BME280_driver/blob/master/bme280.c#L179

https://github.com/BoschSensortec/BMP280_driver/blob/master/bmp280.c#L183

It is probably only necessary to adjust the i2c address in the drivers for these two sensors.

**Comment by deadprogram** [comment]
When I initially tried that, I was getting the "wrong" result. I looked into some Arduino code samples and discovered that the calibration coefficients were named differently.

Perhaps with your greater experience studying the datasheet, you can more easily spot the similarities/differences?

**Comment by deadprogram** [comment]
Hi @dsockwell I have updated my branch to do almost everything except the conversions themselves:

https://github.com/hybridgroup/gobot/blob/feature/i2c/bme280/drivers/i2c/bmp280_driver.go#L165-L173

**Comment by dsockwell** [comment]
oh, yeah, the addresses of the calibration constants are different. check out https://github.com/BoschSensortec/BMP280_driver/blob/master/bmp280.h#L563

**Comment by deadprogram** [comment]
Hi @dsockwell I have updated my branch to do almost everything except the conversions themselves:

https://github.com/hybridgroup/gobot/blob/feature/i2c/bme280/drivers/i2c/bmp280_driver.go#L165-L173
and
https://github.com/hybridgroup/gobot/blob/feature/i2c/bme280/drivers/i2c/bme280_driver.go#L69-L73

**Comment by deadprogram** [comment]
OK nearly there.

Here is the data I am getting back, obviously my conversions are off:

```
Temperature 23.79412
Pressure 65254.918
Humidity -108.65291
```

@dsockwell could you please take a look at my branch and see if you can spot what I'm doing wrong here? Thank you!

**Comment by dsockwell** [comment]
yeah in a few hours

**Comment by deadprogram** [comment]
Thanks!

**Comment by deadprogram** [comment]
Oops, sorry @dsockwell I just noticed your request for some data. Sorry, my bad. I will set things back up to get an accurate data dump later.

**Comment by deadprogram** [comment]
Hi @dsockwell finially got set back up, and figured out what was wrong with my previous attempt to merge some of your code. I got things setup correctly, and now all is working as expected:

```
Temperature 25.155273
Pressure 99185.875
Humidity 50.553627
Temperature 25.165318
Pressure 99191.47
Humidity 50.55474
Temperature 25.170341
Pressure 99192.805
Humidity 50.555317
```

I've merged the branch with the various updates, so I am going to close this one. 

Thank you again for your working on this!

**Pull request closed without merging**
