### PR TITLE
[WIP] add support for VEML7700 (closes #726)

### LINKED ISSUE #726: Sensor request: Adafruit VEML7700 Lux Sensor - I2C Light Sensor
Please support Adafruit VEML7700 Lux Sensor - I2C Light Sensor

https://www.adafruit.com/product/4162

It is I2C so it should be fairly easy.

Both C and Python implementations exist.

### PR DESCRIPTION
**Pull request by szampardi**
## Solved issues and/or description of the change
#726 
...

## Manual test

- OS and Version (Win/Mac/Linux):
- archlinuxarm 6.6.56-1-rpi (rpi0w 2)
- Adaptor(s) and/or driver(s):
- rpi
- i2c
...

## Checklist

- [x] The PR's target branch is 'hybridgroup:dev'
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes (e.g. by run `make test_race`)
- [ ] No linter errors exist locally (e.g. by run `make fmt_check`)
- [x] I have performed a self-review of my own code

If this is a new driver or adaptor:

- [ ] I have added the name to the corresponding README.md
- [ ] I have added an example to see how to setup and use it
- [ ] I have checked or build at least my new example (e.g. by run `make examples_check`)

If this is a PR for release:

- [ ] The PR's target branch is 'hybridgroup:release'
- [ ] I have adjusted the CHANGELOG.md (or already prepared and will be merged as soon as possible)

### CODE REVIEW

**Comment by szampardi** [comment]
@gen2thomas saw that.. luckily I happen to be on semi-vacation so will check the errors out tomorrow morning :D

**Comment by gen2thomas** [comment]
@szampardi no worry - after some month of nearly do nothing for gobot I determine also problems with CircleCI, at least on the UI. Hopefully I can solve this or it does not happen on server.

**Comment by gen2thomas** [comment]
Hi @szampardi , please rebase to dev branch - the CI checks are working.

Thanks Thomas

**Comment by szampardi** [comment]
> please rebase to dev branch

well that didn't go as expected :D

**Comment by gen2thomas** [comment]
From the commit history I think it was a merge not a rebase. After an rebase your commit should be the last (newest) in the history.

**Comment by gen2thomas** [comment]
superseded by #1099

**Pull request closed without merging**
