### PR TITLE
all(bluetooth): adaptors removed to prevent usage of tinygo

### PR DESCRIPTION
**Pull request by gen2thomas**
## Solved issues and/or description of the change

This is just a last resort to make module mode working with v2+ release, see #920 . Affected:
* BLE
* BLE-firmata
* Microbit
* Parrot-Minidrone
* Sphero-BB8, Ollie, Sprkplus

## Manual test

- Linux

## Checklist

- [x] The PR's target branch is 'hybridgroup:dev'
- [x] New and existing unit tests pass locally with my changes (e.g. by run `make test`)
- [x] No linter errors exist locally (e.g. by run `make fmt_check`)
- [x] I have performed a self-review of my own code

If this is a removed driver or adaptor:

- [x] I have removed the names from the README.md
- [x] I have removed examples
- [x] I have run `make examples_check`

### CODE REVIEW

**Comment by deadprogram** [comment]
This is part of Gobot I really quite need. :crying_cat_face:

**Comment by gen2thomas** [comment]
Hi @deadprogram , by prevention of "tinygo/bluetooth" we will lose support for some adaptors, more than I thought. I'm also sad about this. Nevertheless I would test the effect for release of v2+. 

If it works, I will create a new issue for restoring the files. Maybe we can implement a mock package in this case, so the user is able to fast switch to the real implementation. 

If the test is not working, I will restore it immediately and go forward with the v3 approach.

I would do this (merge , release, test, restore/issue) within one or two days until end of this week.

**Comment by deadprogram** [comment]
I guess I still don't fully understand the issue. I thought I added the bluetooth package to a previous release before the whole 2.0 thing?

**Comment by deadprogram** [comment]
See https://github.com/hybridgroup/gobot/issues/920#issuecomment-1578459073

I think this PR here is no longer needed.

**Comment by gen2thomas** [comment]
You are right, unfortunately we have not detected/fixed the root cause yet. Lets see what happen with v3 - if the problem still exist, I will try to implement a mock for tinygo/bluetooth.

**Pull request closed without merging**
