### PR TITLE
add temporary fix to "TestMqttAdaptorConnectWithAuthError"

### PR DESCRIPTION
**Pull request by jadr2ddude**
this fixes the build failure which occurs on many systems (from issue #516)

### CODE REVIEW

**Comment by jadr2ddude** [comment]
I cannot see any particularly good solution. Paho appears to use a public testing server [see this](https://iot.eclipse.org/getting-started#sandboxes). I am not sure how using the testing server would or would not work.

**Comment by jadr2ddude** [comment]
@deadprogram we could potentially reimplement the Client interface in the mqtt package, although that wouldnt help test the connect code. What do you think?

**Comment by deadprogram** [comment]
Basically, that seems like the most pragmatic approach at the moment.

**Comment by trevrosen** [comment]
Hi @jadr2ddude -- thanks for your interest in Gobot! This is the oldest PR currently open, so you've now become a part of my quest to get to PR Inbox Zero 😄 

Do we want to:

1. Declare an interface for the MTT driver in this PR? 
2. Merge as-is? 
3. Close?

 @deadprogram lemme know your preference here when you get a chance. Not hard to do the interface route, which is good to have anyway.

**Comment by jadr2ddude** [comment]
If you want me to modify this, I might have a bit of time in the next few days

**Comment by trevrosen** [comment]
@jadr2ddude any update here?

**Comment by jadr2ddude** [comment]
No. I will be able to set up an MQTT interface this week.

**Comment by trevrosen** [comment]
We can re-visit this with a patch for dependency injection, but I'm going to close this particular patch.

Thanks for the effort here, @jadr2ddude  -- happy to collaborate w/ you if you want to take on the dep injection bit here to make this test a little less janky.

**Pull request closed without merging**
