### PR TITLE
Add basic keyboard driver using `stty`

### PR DESCRIPTION
**Pull request by stewart**
Won't work on Windows unfortunately, but should work on most Unix systems.

### CODE REVIEW

**Comment by deadprogram** [comment]
Works on OSX?

**Comment by stewart** [comment]
That's what I tested it on, would like for Linux users to test it as well though

**Comment by deadprogram** [comment]
Tried on Linux, it worked, however, after terminating the example, the keys I press are no longer displayed in my terminal.

**Comment by deadprogram** [comment]
Looks good now, thanks @stewart

**Pull request merged**
