### PR TITLE
nats: change the On() handler to take the subject as an argument.

### PR DESCRIPTION
**Pull request by nzmichaelh**
Allows wildcard subjects.

Signed-off-by: Michael Hope <mlhx@google.com>

### CODE REVIEW

**Comment by deadprogram** [comment]
Hi @nzmichaelh if you get a chance to update this PR to do the same thing that you did you MQTT as far as passing the message itself to the handler, I could merge it.

Your work on these items is very much appreciated. Thank you!

**Comment by nzmichaelh** [comment]
Hi @deadprogram.  All done.  PTAL.

**Comment by deadprogram** [comment]
Thank you very much for taking care of this @nzmichaelh now merging.

**Comment by DaBlitzStein** [comment]
This is working for queues and subjects?
Thank you.

**Pull request merged**
