### PR TITLE
grovepi driver: Feat/get firmware version

### PR DESCRIPTION
**Pull request by merlindorin**
Add Grovepi get firmware version

must be rebase on https://github.com/hybridgroup/gobot/pull/708 after merge

### CODE REVIEW

**Comment by deadprogram** [comment]
Ready for rebase please @merlindorin if you please and thank you.

**Comment by gen2thomas** [comment]
@merlindorin thank you for your improvement, please could you rebase to resolve the merge conflict?
Afterwards we are able to merge.

**Comment by gen2thomas** [comment]
already done with #870

**Comment by merlindorin** [comment]
Shame on me. Thanks a lot for integrating these changes.

**Comment by gen2thomas** [comment]
You are welcome! It was already well prepared.

**Pull request closed without merging**
