### PR TITLE
Initial ssd1306 driver implementation

### PR DESCRIPTION
**Pull request by llonchj**
This is my first contribution to this project and initial support for [SSD1306 Oled Driver Controller](http://www.solomon-systech.com/en/product/display-ic/oled-driver-controller/ssd1306/) via i2c.

It has been tested with RaspberryPi.

Signed-off-by: Jordi Llonch <llonchj@gmail.com>

### CODE REVIEW

**Comment by deadprogram** [comment]
Hi @llonchj this looks great thanks you very much for working on it!

Could you also please add a simple example program? Thank you again!

**Comment by llonchj** [comment]
Thanks @deadprogram. 
Added the example.

**Comment by deadprogram** [comment]
Thank you @llonchj now merging.

**Comment by llonchj** [comment]
Amazing @deadprogram. Thank you!

**Pull request merged**
