### PR TITLE
dji/tello: add channel to close video to avoid errors on program exit

### PR DESCRIPTION
**Pull request by deadprogram**
THis PR fixes the crash on exit when streaming video with the DJI Tello by adding a channel to close video to avoid errors on program exit.

### CODE REVIEW

**Comment by gen2thomas** [comment]
Hi @deadprogram , this implementation looks similar to the one prepared in #793 . Please could you have a look in it and maybe link this PR as the solution for the issue. Also the provided test cases would be helpful to prevent this problem in the future.

**Comment by deadprogram** [comment]
I will take a look for sure, thanks for pointing that out @gen2thomas

**Comment by deadprogram** [comment]
OK I see what you meant @gen2thomas the solution proposed by @st-user is more complete.

@st-user sorry about the delayed response. Are you willing to submit a PR with that code, or alternatively let us git cherry-pick it into a PR?

**Comment by st-user** [comment]
Thank you for checking the issue.

I made a pull about #793.
(https://github.com/hybridgroup/gobot/pull/858)

I hope this solution helps!

**Comment by deadprogram** [comment]
No longer needed thanks to #858

**Pull request closed without merging**
