### PR TITLE
Add a Stream type that handle the request to /events/:event and write tests for event stream

### PR DESCRIPTION
**Pull request by rafmagana**
* Test coverage for event stream
* Fixes json error when event doesn't exists

### CODE REVIEW

**Comment by rafmagana** [comment]
@zankich  The time the test suite takes to run was increased more than 2 seconds, don't know if that's a problem for Travis because it doesn't say what the problem was, I didn't find another way to test the events stream, I'll check this out tomorrow morning.

**Comment by rafmagana** [comment]
@zankich a test is failing in Go 1.2, I only tested locally with Go 1.3, so I'm going to install go 1.2 and see what's the problem.

**Comment by rafmagana** [comment]
@zankich I added another way to test the `/events/:event` endpoint, I realized that in the first way I did it I was only testing if the value was being sent to the channel not the actual response, in my last commit I test the actual response (and it works with Go 1.2), please, check it out and let me know.

**Comment by zankich** [comment]
:shaved_ice:

**Pull request merged**
